
## `.github/workflows/docs.yml`
```yaml
name: Docs
on: [push, pull_request]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: python -m pip install -U pip
      - run: pip install -e .
      - run: pip install -r docs/requirements.txt
      - run: sphinx-apidoc -o docs/api src/your_project -f -e
      - run: sphinx-build -b html docs docs/_build/html

